Algoritmo "Escreve tela"
// Disciplina   : [Criação de aplicações]
// Professor   : Franklin Portela
// Descrição   : Pega o nome e escreve na tela
// Autor(a)    : Mauricio Souza Caetano
// Data atual  : 03/04/2022
Var
// Seção de Declarações das variáveis 
nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Qual seu primeiro nome?")
leia (nome)
escreva ("Obrigado ", nome, "!")

Fimalgoritmo