Algoritmo "EstruturaDeRepetição"
// Disciplina   : [Linguagem e Lógica de Programação]

// Descrição   : exemplo de contador na linguagem visualg

Var
// Seção de Declarações das variáveis
contador,limite,resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para limite de 0 ate 9 faca
   resultado <- 9* contador
   contador <- contador + 1
   Escreval(resultado)
   Escreval(contador)
fimpara
Escreval(resultado)

Fimalgoritmo