Algoritmo "ExEntradaProcessamentoSaida"

Var
// Seção de Declarações das variáveis 
num1: real
num2: real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o primeiro número: ")
leia(num1)
escreval("Digite o segundo número: ")
leia(num2)
resultado <- num1*num2
escreval("O primeiro número é: ", num1)
escreval("O segundo número é: ", num2)
escreval("O resultado é = ", resultado)
Fimalgoritmo