Algoritmo "WhoisLower"
Var
// Seção de Declarações das variáveis 
num1, num2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o primeiro número: ")
leia(num1)
Escreval("Digite o segundo número: ")
leia(num2)
Se (num1 < num2) entao
Escreval("O número maior é = ", num2)
Senao
Escreval("Os dois números são respectivamente: ", num1," e", num2)
FimSe

Fimalgoritmo